version: "2"
linters:
  enable:
    - bodyclose
    - contextcheck
    - gocritic
    - misspell
    - noctx
    - revive
    - wrapcheck
  settings:
    revive:
      rules:
        - name: exported
        - name: unused-parameter
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/iyashjayesh/gostart
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
